version: "3"

services:
  db:
    container_name: db
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: person
      MYSQL_PASSWORD: password
    ports:
      - "3333:3306"
    networks:
      - tp-2903-net
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3333
    networks:
      - tp-2903-net
  api:
    depends_on:
      - db
    restart: always
    build: 
      context: ./person_restapi
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    networks:
      - tp-2903-net
  front:
    depends_on:
      - api
    restart: always
    build: 
      context: ./person_front
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - tp-2903-net


networks:
  tp-2903-net:
    driver: bridge

volumes:
  db_data: