version: "3"

services:
  db:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: person
      MYSQL_PASSWORD: password
    networks:
      - tp-2903-net
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
    networks:
      - tp-2903-net

networks:
  tp-2903-net:
    driver: bridge

volumes:
  db_data: